#include "system_admin.h"

void system_admin_addcompany_ui() {
	string system_status;
	string space = string(Width, double2);
	body();
	fcolor(main_bordr_color);
	bcolor(main_back_color);
	time_t now = time(0);
	struct tm ltm;
	localtime_s(&ltm, &now);
	string date = to_string(ltm.tm_mday) + "  /  " + to_string(1 + ltm.tm_mon) + "  /  " + to_string(1900 + ltm.tm_year);
	string dashboard = "SYSTEM ADMINISTRATION CONSOLE (Add Company)";
	white(Bfont);
	bold;
	move(2, centerS(dashboard));
	cout << dashboard;
	move(0, centerS(date));
	cout << date;
	fcolor(main_bordr_color);
	move(1, 0);cout << double9 << space << double10;
	move(3, 0);cout << double9 << space << double10;
	cout << system_status;
	footer(roles[0], 2);
	fcolor("100;210;255");
	move(5,centerS(((string)"Company Name")));
	cout << "Company Name";
	move(10,centerS(((string)"Company Domain")));
	cout << "Company Domain";
	move(6, 3);
	move(15,centerS(((string)"Company ID")));
	cout << "Company ID";
	move(6, 3);
	bcolor(main_boxback_color);
	Dframe(1, 39);
	move(11, 3);
	Dframe(1, 39);
	move(16, 3);
	Dframe(1, 39);
	fcolor(botton_border_color);
	bcolor(botton_color);
	move(21, 3);
	Dframe(1, 15);
	move(21, 27);
	Dframe(1, 15);
	fcolor(botton_font_color);
	move(22, centerLN(4, 19, ((string)"Add")));
	cout << "Add";
	move(22, centerLN(28, 42, ((string)"Cancel")));
	cout << "Cancel";
}